---
- hosts: server
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      when: ansible_os_family == 'Debian'
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Upgrade all packages on debian servers
      when: ansible_os_family == 'Debian'
      apt: upgrade=yes force_apt_get=yes